### ISSUE TITLE
Add option to be verbose

### ISSUE THREAD

**Issue by jtheriault** [meltwater/awsudo#15]
The default behavior of awsudo should facilitate being a drop-in enhancement over the AWS cli. Status messages such as the [role ARN notification](https://github.com/meltwater/awsudo/blob/1e88fb3a3816a473c7fd07fb223d6ec10bb135c9/bin/awsudo#L11) may break that by changing the output.

Status messages should be suppressed by default and re-enabled with a -v or --verbose option.

**Comment by terodox** [comment]
This was release with version 1.0.0 see [release notes here](https://github.com/meltwater/awsudo/releases/tag/v1.0.0)
