### ISSUE TITLE
Add option to customize role session name

### ISSUE THREAD

**Issue by ozeebee** [meltwater/awsudo#33]
Hi, it would be nice to be able to customize the role session name !
Thanks,

Alain

**Comment by terodox** [comment]
Hi @ozeebee! Thank you for using awsudo!

Is this a feature you would feel comfortable opening a pull request for?

**Comment by ozeebee** [comment]
Hi, yep I can do it but I'm so busy right now, I'm afraid I won't be able to implement it before next year.
Anyway, I think this would be an interestnig option (for auditing purposes).

**Comment by terodox** [comment]
Ok, we'll see if we can get it implemented before the new year. If we are unable to find time before you, a PR would be awesome!

**Comment by terodox** [comment]
Thanks again @ozeebee for your PR!
