### ISSUE TITLE
Does not support AWS partitions

### ISSUE THREAD

**Issue by gianlucb** [meltwater/awsudo#47]
Hi,

I'm would like to use this package to run AWS CLI commands on several AWS accounts. Looks like this does not support all AWS partions (i.e: **aws-cn**, **aws-us-gov**):

https://github.com/meltwater/awsudo/blob/0eb8794d09eeca8cce4c699435ff531108969c4f/bin/awsudo#L79

is there any plan to support the different aws partitions?

**Comment by terodox** [comment]
This hasn’t been a use case we’ve needed. We do accept prs though! We’d be happy to merge a PR to expand to other partitions
