### ISSUE TITLE
Feature: revoke sts token after command finishes executing

### ISSUE THREAD

**Issue by terodox** [meltwater/awsudo#61]
Because the sts token is only valid for the duration of the command.

I would love to see STS credentials being revoked at the end of a command to ensure we are not persisting anything that could be used maliciously.

Relevant AWS documentation:
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_revoke-sessions.html

**Comment by jtheriault** [comment]
This was address by #64 and released in [v2.0.0](https://github.com/meltwater/awsudo/releases/tag/v2.0.0)
