### ISSUE TITLE
Inconsistent retrieval of ENV vars in bash file

### ISSUE THREAD

**Issue by perbergland** [meltwater/awsudo#7]
The last lines in the awsudo file are inconsistent - row two is the only one that has leading period and without executing it, I would guess that the other three should have that too.
I would also encourage quoting the CREDENTIALS in case they have characters that the shell consider special (i.e. echo "${CREDENTIALS}" | …)

```
export AWS_ACCESS_KEY_ID=`echo ${CREDENTIALS} | json.js Credentials.AccessKeyId`
export AWS_SECRET_ACCESS_KEY=`echo ${CREDENTIALS} | json.js .Credentials.SecretAccessKey`
export AWS_SESSION_TOKEN=`echo ${CREDENTIALS} | json.js Credentials.SessionToken`
export AWS_EXPIRATION=`echo ${CREDENTIALS} | json.js Credentials.Expiration`
```

**Comment by terodox** [comment]
Good feedback @perbergland!
